### ISSUE TITLE
Update to tables-3.3.0

### ISSUE THREAD

**Issue by frostbtn** [MacPython/pytables-wheels#1]
@matthew-brett,
PyTables 3.3.0 [is out](https://github.com/PyTables/PyTables/releases/tag/v3.3.0).
Would you please kick a build for it?

**Comment by andreabedini** [comment]
ah, I should have done it. I'll read up how to do it :)

**Comment by andreabedini** [comment]
@matthew-brett not sure if I should update the submodule or not?

**Comment by matthew-brett** [comment]
No need to update the submodule - you only need to change the BUILD_COMMIT
- but I see you have.

Build looks fine, now you can upload to pypi - see the instructions in the
README.   Any questions, please do ask.
​

**Comment by frostbtn** [comment]
Thanks, guys!

**Comment by andreabedini** [comment]
sorry I am a bit swamped these days and I haven't found the time to upload the wheels yet, @tomkooij do you have time to do it?

**Comment by matthew-brett** [comment]
If someone gives me permission in pyoi I am happy to do it

matthew.brett  on pypi

**Comment by andreabedini** [comment]
@matthew-brett done, thank you for all the work Matthew

**Comment by matthew-brett** [comment]
Wheels signed and uploaded.  Happy to help.​
