### ISSUE TITLE
Use -headerpad_max_install_names on Mac OSX wheels

### ISSUE THREAD

**Issue by tomkooij** [MacPython/pytables-wheels#13]
Ref: https://github.com/PyTables/PyTables/issues/673

**Comment by FrancescAlted** [comment]
PyTables/PyTables#673 references the `libsz.2.dylib` , but I cannot see the way to produce this in config.sh.  I assume `libsz.2.dylib` should be produced as part of `libhdf5`?

**Comment by peircej** [comment]
I think this can be closed. The issue got resolved in py2app so that the `-headerpad_max_install_names` flag isn't needed elsewhere in the end.
