### ISSUE TITLE
OSX builds fail for python 3.6

### ISSUE THREAD

**Issue by tomkooij** [MacPython/pytables-wheels#3]
I started linux and OSX builds for python 3.6: 78ceb8a. (Windows builds successful and uploaded to PyPI).

~~Linux: pip complains about incompatible NumPy API. Probably fixable by requiring a different NumPy.~~ Fixed.
OSX: Fails. Failed build: https://travis-ci.org/MacPython/pytables-wheels/jobs/205484823

@matthew-brett : Any thoughts?

**Comment by matthew-brett** [comment]
I think you need numpy 1.11.3 for Python 3.6 - it's the only wheel available for Python 3.6, and all the other Python 3.6 packages are built against it - I tried that in commit f1ff67b.

**Comment by tomkooij** [comment]
Very nice! Wheels are built. I cannot test the Mac wheel, so I won't upload it to PyPI. I'll leave that to you.
Thanks!

**Comment by matthew-brett** [comment]
I generally assume that that the OSX wheel is OK, from the fact that the tests pass on the VM.  It installs and imports fine on my machine.  I've uploaded it.

**Comment by tomkooij** [comment]
Thanks!
