### ISSUE TITLE
Linux (OSX?) wheels build against installed blosc instead of builtin blosc

### ISSUE THREAD

**Issue by tomkooij** [MacPython/pytables-wheels#5]
See PyTables/Pytables#219

The installed blosc can be older than builtin blosc --> prefer builtin.

**Comment by matthew-brett** [comment]
At the moment the wheels build against a given version of blosc given in the `config.sh` file.

This triggers the build recipe in `multibuild/library_installers.sh`, which is pretty standard apart from an OSX install name fix.

I don't know whether this fix is still needed or effective for new versions of c-blosc - here is the relevant c-blosc issue: https://github.com/Blosc/c-blosc/issues/175 .  I think @FrancescAlted fixed the immediate issue by using @RPATH (via cmake), which will mess up the ability of `delocate` to find the library and package it into the wheel - see : https://github.com/Blosc/c-blosc/commit/980779d0fc25880547eb024cfe2e7ef22789e630#commitcomment-18464526

**Comment by FrancescAlted** [comment]
But the point is that PyTables should not need to link with an external Blosc library, but rather use the internal sources, so we wouldn't need to wrestle with @RPATH or similar (unless I am missing something).

**Comment by matthew-brett** [comment]
Sure - if the internal blosc doesn't use the same compilation method, I guess it will likely be fine.

**Comment by tomkooij** [comment]
Fixed in #6
